#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
 yarn lint \"src/**/*.ts\" \"test/**/*.ts\" --fix ;if git --no-pager diff HEAD package.json | egrep '\"version\": \"[0-9]+\\.'; then npm run version; else (npm --no-git-tag-version version patch; git add package.json;); fi;
chmod ug+x .husky/* 
yarn lint && yarn pretty-quick --staged
